### ISSUE TITLE
Example for terraform resources?

### ISSUE THREAD

**Issue by yujunz** [stripe/skycfg#22]
The README says it can also used for terraform resources. Is there an example?

**Comment by jmillikin-stripe** [comment]
There isn't an example for Terraform yet. Internally we're using Terraform's [JSON syntax](https://www.terraform.io/docs/configuration/syntax.html#json-syntax) and the ["external" data source](https://www.terraform.io/docs/providers/external/data_source.html) to pass data from Skycfg-enabled helper binaries into the Terraform modules.

**Comment by yujunz** [comment]
Thanks
