### ISSUE TITLE
Envoy's SocketAddress.port_value can be > 65535?

### ISSUE THREAD

**Issue by pcn** [stripe/skycfg#48]
How is the validation rule in https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/core/address.proto#L50 treated? I would expect that using that here: https://github.com/pcn/followprotocol/blob/master/envoy.sky#L72 would result in a failure since it's defined as an int32 but less than or equal to 65535. What's required to have this limit observed in skycfg?

**Comment by dilyevsky** [comment]
Pretty sure these are completely ignored as they are from Lyft's custom protobuf plugin.

**Comment by pcn** [comment]
OK, interesting. I'm not very famliar with the landscape. So do you mean https://github.com/lyft/protoc-gen-validate? Does that mean that there should be a validate method in there? Is there a way to invoke that in my skycfg?

**Comment by dilyevsky** [comment]
It creates Validate methods for your types using codegen. You should
probably not call it in starlark since it seems more of an implementation
detail and call it on the output msgs of skycfg library instead (besides
this project is alpha atm).
