### ISSUE TITLE
field updates to an appended proto aren't reflected from the enclosing proto message

### ISSUE THREAD

**Issue by yq-stripe** [stripe/skycfg#60]
Given a field typed as a repeated message, it seems that in skycfg, after appending a new proto to this repeated field, then indexing into the list later to make changes to that proto those changes aren't reflected when viewing/converting the enclosing message. 

for example, 

```
message one {
   repeated two twos = 1;
}
message two {
   string val = 1;
}
```

```
def main(ctx):
  one = foo.one()
  one.twos.append(foo.two())
  one.twos[0].val = 'something'
  print(one) // [val] is missing from two
  print(one.twos)  // [val] is there
  return [one] 
```

For some reason it seems that the field update is there when accessing `one.twos` but when referring to the enclosing message `one` the field update is lossed, e.g. `proto.to_text(one)`, `proto.to_yaml(one)` etc don't show one.twos[0] with `val` set. 

It also seems to work perfectly fine if you replace `one.twos.append(foo.two())` with `one.twos = [foo.two()]`. Started looking into the code but no luck so far to why.

**Comment by dilyevsky** [comment]
ooh that was a good one - nice find! Sent #61
