### ISSUE TITLE
go/protobuf api v2: Should skycfg migrate to v2?

### ISSUE THREAD

**Issue by dilyevsky** [stripe/skycfg#80]
Some pros/cons of the migration I could think of:

Pros:
* Cleaner/smaller codebase
* Dynamic message support (in relation to https://github.com/stripe/skycfg/issues/79#issue-625374894)

Cons:
* Unclear Gogo Protobuf support - duplicate both apis or drop support entirely?

**Comment by jmillikin-stripe** [comment]
See https://github.com/stripe/skycfg/issues/15

If gogo doesn't support the standard Go protobuf library then we can work that out separately.
